<div id="page:main-container">
    <div class="content-header">
        <h3 class="icon-head">Product Creator</h3>
        <div class="content-buttons-placeholder">
            <p class="content-buttons form-buttons">
                <button class="scalable ">
                    <span>
                        <span>
                            <span>Create Product</span>
                        </span>
                    </span>
                </button>
            </p>
        </div>
    </div>
</div>
<form action="<?php echo Mage::helper('adminhtml')->getUrl('productcreator/adminhtml_productcreatorbackend/create'); ?>" method="post">
    <input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend">Add a new Product</h4>
        </div>
    </div>
    <div id="base_fieldset" class="fieldset fieldset-wide">
        <table class="form-list">
            <tbody>
                <tr>
                    <td class="label"><label for="product name">Product Name</label></td>
                    <td class="value">
                        <input type="text" class=" input-text required-entry" title="Template Name" value="" name="name">
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label for="">Sku</label>
                    </td>
                    <td class="label">
                        <input type="text" name="sku"/>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label for="">Paper Sizes</label>
                    </td>
                    <td class="label">
                        <?php $papersizes = $this->getAttributeOptions('paper_size') ?>
                        <select name="paper_size[]" id="" multiple="">
                            <?php foreach ($papersizes as $papersize): ?>
                                <option value="<?php echo $papersize['value'] ?> "><?php echo $papersize['label'] ?></option>
                            <?php endforeach ?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label for="">Finish</label>
                    </td>
                    <td class="label">
                        <?php $finishes = $this->getAttributeOptions('finish') ?>
                        <select name="finish[]" id="" multiple="">
                            <?php foreach ($finishes as $finish): ?>
                                <option value="<?php echo $finish['value'] ?> "><?php echo $finish['label'] ?></option>
                            <?php endforeach ?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label for="">Paper Weight</label>
                    </td>
                    <td class="label">
                        <?php $paperweights = $this->getAttributeOptions('paper_weight') ?>
                        <select name="paper_weight[]" id="" multiple="">
                            <?php foreach ($paperweights as $paperweight): ?>
                                <option value="<?php echo $paperweight['value'] ?> "><?php echo $paperweight['label'] ?></option>
                            <?php endforeach ?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label for="">Colour</label>
                    </td>
                    <td class="label">
                        <?php $colours = $this->getAttributeOptions('colour') ?>
                        <select name="colour[]" id="" multiple="">
                            <?php foreach ($colours as $colour): ?>
                                <option value="<?php echo $colour['value'] ?> "><?php echo $colour['label'] ?></option>
                            <?php endforeach ?>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label for="">Sides</label>
                    </td>
                    <td class="label">
                        <?php $sides = $this->getAttributeOptions('sides') ?>
                        <select name="sides[]" id="" multiple="">
                            <?php foreach ($sides as $side): ?>
                                <option value="<?php echo $side['value'] ?> "><?php echo $side['label'] ?></option>
                            <?php endforeach ?>
                        </select>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <input type="submit" value="submit" />
</form>
<!--<form action="/que.php" method="post">
    <p>
        <label for="">Sku</label>
        <input type="text" name="sku"/>
    </p>
    <p>
        <label for="">Name</label>
        <input type="text" name="name"/>
    </p>
    <p>
        <label for="">Description</label>
        <textArea name="description">
                    
                </textArea>
            </p>
            <p>
                <label for="" >Color</label>
                <select name="color[]" multiple>
                    <option value="6">Blue</option>
                    <option value="7">Green</option>
                    <option value="8">Yellow</option>
                    <option value="9">Red</option>
                </select>
            </p>
            <p>
                <label for="">Size</label>
                <select name="size[]" multiple="">
                    <option value="3">15</option>
                    <option value="5">12</option>
                    <option value="4">10</option>
                </select>
            </p>
            <p>
                <input type="submit" value="Submit"/>
            </p>
        </form>-->