<div id="page:main-container">
    <div class="content-header">
        <h3 class="icon-head">Product Creator</h3>
        <div class="content-buttons-placeholder">
            <p class="content-buttons form-buttons">
                <button class="scalable ">
                    <span>
                        <span>
                            <span>Create Product</span>
                        </span>
                    </span>
                </button>
            </p>
        </div>
    </div>
</div>
<form action="">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-edit-form fieldset-legend">Add a new Product</h4>
        </div>
    </div>
    <div id="base_fieldset" class="fieldset fieldset-wide">
        <table class="form-list">
            <tbody>
                <tr>
                    <td class="label"><label for="product name">Product Name</label></td>
                    <td class="value">
                        <input type="text" class=" input-text required-entry" title="Template Name" value="" name="code" id="code">
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label for="">Sku</label>
                    </td>
                    <td class="label">
                        <input type="text" />
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label for="">Paper Sizes</label>
                    </td>
                    <td class="label">
                        <select name="" id="" multiple="">
                            <option value="">A1</option>
                            <option value="">A2</option>
                            <option value="">A3</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label for="">Paper Weight &amp Finish</label>
                    </td>
                    <td class="label">
                        <select name="" id="" multiple="">
                            <option value="">100 gsm Matt Finish (Uncoated)</option>
                            <option value="">100 gsm Matt Finish (coated)</option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label for="">Items Per Sheet</label>
                    </td>
                    <td class="label">
                        <input type="text" />
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label for="">Sides</label>
                    </td>
                    <td class="label">
                        <input type="text" />
                    </td>
                </tr>
                <tr>
                    <td class="label">
                        <label for="">Quantities</label>
                    </td>
                    <td class="label">
                        <select name="" id="" multiple="">
                            <option value="">10,15</option>
                            <option value="">15,50</option>
                        </select>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</form>

<!--<form action="/que.php" method="post">
    <p>
        <label for="">Sku</label>
        <input type="text" name="sku"/>
    </p>
    <p>
        <label for="">Name</label>
        <input type="text" name="name"/>
    </p>
    <p>
        <label for="">Description</label>
        <textArea name="description">
                    
                </textArea>
            </p>
            <p>
                <label for="" >Color</label>
                <select name="color[]" multiple>
                    <option value="6">Blue</option>
                    <option value="7">Green</option>
                    <option value="8">Yellow</option>
                    <option value="9">Red</option>
                </select>
            </p>
            <p>
                <label for="">Size</label>
                <select name="size[]" multiple="">
                    <option value="3">15</option>
                    <option value="5">12</option>
                    <option value="4">10</option>
                </select>
            </p>
            <p>
                <input type="submit" value="Submit"/>
            </p>
        </form>-->